[discord]


[bridge]
max_message_length = 70
# URL của Cloudflare Worker (thay đổi khi deploy xong)
worker_url = https://maple-discord-bridge.dutch25.workers.dev/
machine_name = dutch
pusher_key = 0233d516a943fa684018
pusher_cluster = ap1

